channels:
- conda-forge
dependencies:
- jupyterlab=3
#- nodejs
#- ipython
#- ipywidgets=7.5.1
#- notebook
#- ipykernel
- nglview=2.7.7
#- rdkit::rdkit
#- pip:
    #- pytraj
    #- ipython_blocking
    #- moviepy