channels:
- conda-forge
dependencies:
- jupyterlab=3
#- nodejs
- ipython
#ipywidgets>=7.6.0,<8
- ipywidgets=7.6.5 
#- notebook
#- ipykernel
- nglview
#- rdkit::rdkit
#- pip:
    #- pytraj
    #- ipython_blocking
    #- moviepy