channels:
- conda-forge
dependencies:
- jupyterlab=3
#- nodejs
- ipython
#ipywidgets>=7.6.0,<8
- ipywidgets=8.0.4 
#- notebook
#- ipykernel
- nglview=3.0.3
- biopython
#- rdkit::rdkit
#- pip:
    #- pytraj
    #- ipython_blocking
    #- moviepy